# Database connection
db.url=jdbc:mysql://localhost:3306/atmdb
db.username=root
db.password=root
db.driver=com.mysql.cj.jdbc.Driver

# Connection pool
db.pool.max=10
#minIdle -> if the traffic occurs the 2 of them is allocated or used 
db.pool.minIdle=2 

SECRET=12345678901234567890123456789012
EXPIRATION_MS=3600000

# email configuration
mail.host=smtp.gmail.com
mail.port=587
mail.username=aswin.c2401@gmail.com
mail.password= qdku kgld azll zcxd

#  logging
org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss
org.slf4j.simpleLogger.log.com.atm.controller.LoginServlet=debug
org.slf4j.simpleLogger.log.com.atm.service.AuthService=info

#Swagggrt api
swagger.title=ATM API
swagger.version=1.0.0
swagger.description=ATM system APIs for login, deposit, withdraw, balance, transactions

feature.enabled=false
