services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: atmdb
    volumes:
      - mysql_data:/var/lib/mysql
 
  app:
    image: aswin.c/atmdb:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      
volumes:
  mysql_data: